/* Generated by tools/build.mjs. Do not edit by hand. */
window.ZOE_CONFIG = {
  "formEndpoint": null,
  "newsletterEndpoint": null,
  "bookingUrl": null,
  "payments": {
    "devotional": {
      "stripe": null,
      "paypal": null
    },
    "journal": {
      "stripe": null,
      "paypal": null
    }
  }
};
