/* Generated by tools/build.mjs. Do not edit by hand. */
window.ZOE_CONFIG = {
  "formEndpoint": "https://script.google.com/macros/s/AKfycbytoV9xN3J79pHvXy67VMONMc8MXwC5vf5DuwdrSyxy8ej0BwUGLe92KMmsjZimQNeu/exec",
  "newsletterEndpoint": "https://script.google.com/macros/s/AKfycbytoV9xN3J79pHvXy67VMONMc8MXwC5vf5DuwdrSyxy8ej0BwUGLe92KMmsjZimQNeu/exec",
  "bookingUrl": "https://calendar.app.google/Uj9v44HE72kJrKz8A",
  "paidBookingUrl": null,
  "payments": {
    "devotional": {
      "amazon": null,
      "etsy": null,
      "gumroad": null,
      "stripe": null,
      "paypal": null
    },
    "journal": {
      "amazon": null,
      "etsy": null,
      "gumroad": null,
      "stripe": null,
      "paypal": null
    }
  }
};
