/* Generated by tools/build.mjs. Do not edit by hand. */
window.ZOE_CONFIG = {
  "formEndpoint": "https://formsubmit.co/ajax/contact@zoelifehub.com",
  "newsletterEndpoint": "https://formsubmit.co/ajax/contact@zoelifehub.com",
  "bookingUrl": "https://calendar.app.google/Uj9v44HE72kJrKz8A",
  "payments": {
    "devotional": {
      "stripe": null,
      "paypal": null
    },
    "journal": {
      "stripe": null,
      "paypal": null
    }
  }
};
