import {mkdtempSync, cpSync, readFileSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, relative, sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('..', import.meta.url));
const temp=mkdtempSync(join(tmpdir(),'zoe-build-'));
try {
 cpSync(root,temp,{recursive:true,filter:src=>!relative(root,src).split(sep).some(part=>['.git','node_modules','.stripe-sandbox','screenshots','.chrome-qa','.chrome-qa-forms','.chrome-verify','.chrome-artifact'].includes(part))});
 const env={...process.env,ZOE_FORM_ENDPOINT:'https://script.google.com/macros/s/test/exec',ZOE_NEWSLETTER_ENDPOINT:'https://script.google.com/macros/s/test/exec',ZOE_GOOGLE_CALENDAR_BOOKING_URL:'https://calendar.app.google/Uj9v44HE72kJrKz8A',ZOE_PAID_BOOKING_URL:'https://calendar.google.com/calendar/appointments/schedules/test',ZOE_AMAZON_DEVOTIONAL_URL:'https://www.amazon.com/dp/TEST',ZOE_GUMROAD_JOURNAL_URL:'https://example.gumroad.com/l/test'};
 let run=spawnSync(process.execPath,['tools/build.mjs','--staging'],{cwd:temp,env,encoding:'utf8'});
 assert.equal(run.status,0,run.stderr);
 run=spawnSync(process.execPath,['tests/check-site.mjs'],{cwd:temp,env,encoding:'utf8'});
 assert.equal(run.status,0,run.stdout+run.stderr);
 assert.match(readFileSync(join(temp,'consult.html'),'utf8'),/href="https:\/\/calendar.google.com\/calendar\/appointments\/schedules\/test"/);
 assert.match(readFileSync(join(temp,'books.html'),'utf8'),/Buy on Amazon/);
 assert.match(readFileSync(join(temp,'books.html'),'utf8'),/Buy on Gumroad/);
 assert.match(readFileSync(join(temp,'contact.html'),'utf8'),/I agree to join Zoe Life's mailing list and can unsubscribe at any time\. We will email you a link to confirm\./);
 assert.doesNotMatch(readFileSync(join(temp,'contact.html'),'utf8'),/Google Workspace|FormSubmit|store my signup/);
 run=spawnSync(process.execPath,['tools/build.mjs'],{cwd:temp,env:{...env,ZOE_PAID_BOOKING_URL:'javascript:alert(1)'},encoding:'utf8'});
 assert.notEqual(run.status,0);
 const sandboxEnv={...env,ZOE_STAGING:'0'};
 run=spawnSync(process.execPath,['tools/build.mjs','--stripe-sandbox'],{cwd:temp,env:sandboxEnv,encoding:'utf8'});
 assert.notEqual(run.status,0);
 assert.match(run.stderr,/sandbox requires --staging/);
 run=spawnSync(process.execPath,['tools/build.mjs','--staging','--stripe-sandbox'],{cwd:temp,env:sandboxEnv,encoding:'utf8'});
 assert.equal(run.status,0,run.stderr);
 const sandboxBooks=readFileSync(join(temp,'books.html'),'utf8');
 const sandboxConfig=JSON.parse(readFileSync(join(temp,'integrations/stripe/sandbox.json'),'utf8'));
 for (const product of Object.values(sandboxConfig.products)) assert.ok(sandboxBooks.includes(product.paymentLink));
 assert.equal((sandboxBooks.match(/Test Stripe checkout/g)||[]).length,2);
 assert.match(sandboxBooks,/No real payment or book delivery/);
 assert.doesNotMatch(sandboxBooks,/Buy on Amazon|Buy on Gumroad/);
 run=spawnSync(process.execPath,['tests/check-site.mjs'],{cwd:temp,env:sandboxEnv,encoding:'utf8'});
 assert.equal(run.status,0,run.stdout+run.stderr);
 run=spawnSync(process.execPath,['tools/build.mjs'],{cwd:temp,env:{...sandboxEnv,ZOE_STRIPE_DEVOTIONAL_URL:sandboxConfig.products.devotional.paymentLink},encoding:'utf8'});
 assert.notEqual(run.status,0);
 assert.match(run.stderr,/test Payment Links cannot be used in production/);
 run=spawnSync(process.execPath,['tools/build.mjs'],{cwd:temp,env:{...sandboxEnv,ZOE_COURSE_ENGAGED_FIRST_YEAR_URL:sandboxConfig.products.devotional.paymentLink},encoding:'utf8'});
 assert.notEqual(run.status,0);
 assert.match(run.stderr,/test Payment Links cannot be used in production/);
 run=spawnSync(process.execPath,['tools/build.mjs','--staging'],{cwd:temp,env:{...env,ZOE_COURSE_COMMITTED_URL:'https://buy.stripe.com/b/committedlive'},encoding:'utf8'});
 assert.equal(run.status,0,run.stderr);
 const paidCourses=readFileSync(join(temp,'courses.html'),'utf8');
 assert.match(paidCourses,/https:\/\/buy\.stripe\.com\/b\/committedlive/);
 assert.match(paidCourses,/Buy this track/);
 assert.doesNotMatch(readFileSync(join(temp,'courses/welcome.html'),'utf8'),/fetch\s*\(|script\.google\.com/);
 console.log('Passed: Workspace, paid booking, storefronts, Stripe sandbox links and labels, static checks, staging enforcement, production test-link rejection, unsafe URL rejection.');
} finally {rmSync(temp,{recursive:true,force:true});}
